'''
These are the default params that could be used by the preprocessor in utils.py.
'''

# ============================================
# ======  Parameters for Preprocessing  ======
# ============================================

data_preprocessor:
  eeg_cap_type: gel64               # from 'gel64', 'dry64', or 'saline64'.
  sampling_frequency: 1000          # sampling frequency. Data recorded with ANT EEGO is 1000 Hz by default.
  ch_to_drop:                       # channel names we want to drop.
    - TRGR
    - COUNT
    - F7
    - F5
    - F3
    - F1
    - Fz
    - F2
    - F4
    - F6
    - F8
    - Fp1
    - Fpz
    - Fp2
    - AF7
    - AF3
    - AF4
    - AF8
    - EOG
  bandpass_filter:
<<<<<<< HEAD
    apply: True                    # whether bandpass filter is needed.
=======
    apply: False                    # whether bandpass filter is needed.
>>>>>>> 560492032b22dc7ef6f0d484b3997a263227b2fb
    lowcut: 4                       # the low pass band.
    highcut: 40                     # the high pass band.
    order: 5                        # the order of the filter.
